### ISSUE TITLE
Problem with Cyrillic

### ISSUE THREAD

**Issue by azubkokshe** [grailbio/go-netdicom#10]
Hello! When i send cyrillic symbols from Weasis viewer in C-FIND request (ex. "привет") in SCP i receive: 2021/02/09 17:53:42 CFind: filter  (0010,0010)[PatientName] PN  [??????] <----

How to report to SCU use fo example ISO IR 192?

**Comment by azubkokshe** [comment]
@yasushi-saito

**Comment by Ruxton** [comment]
I'm no expert, but shouldn't your C-Find filters be sent in with tag 0008,0005 for SpecificCharacterSet set?

You can see how the sampleclient forces this to ISO_IR 100 when generating a C-Find at https://github.com/grailbio/go-netdicom/blob/master/sampleclient/sampleclient.go#L61

**Comment by azubkokshe** [comment]
thanks, I solved it yesterday. weasis replaces the Cyrillic alphabet with the "?"
