### ISSUE TITLE
Problem on communicating with GEPACS

### ISSUE THREAD

**Issue by Successus-Littera** [grailbio/go-netdicom#7]
First of all, thank you for sharing fantastic ideas in here.

I met the issue when I tried to communicate with our existing PACS server.

I think the code should produce .dcm file appropriately but it wasn't.

I used your sample code "sampleserver.go" for test.

I got bytes array from the server and it seems good.
(Which is finely working in python, pynetdicom)

But sadly go-netdicom is not working properly.

I attach the bytes array i got.

Please review this issue.

**Comment by Successus-Littera** [comment]
[https://drive.google.com/open?id=1CwxiiAbXxh814tLw543_0l7gKmqMV4yl](url)

and this coummunication has transferSyntaxUID as follow :
2.16.840.1.113709.1.2.2

which doesn't exist in uid.go, so i put it in.

**Comment by siddharthab** [comment]
Sorry, but we are no longer working on this project and are archiving this repository.
